---
title: "ward map"
author: "Yi Ning"
date: "10/24/2020"
output: html_document
---
```{r}
list.of.packages <- c("tidyverse", 
                      "readr",
                      "usethis",
                      "sf",
                      "viridis",
                      "rmapzen"
                      )

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]

library()
if(length(new.packages)) install.packages(new.packages)

#load all required packages
lapply(list.of.packages, require, character.only = TRUE)
```

```{r}

summary_commarea = read.csv("~/GitHub/Peoples Budget Viz/peoples-budget-viz/visualize/csvs/Peoples_Budget_user_summary_COMMUNITY_AREA.csv")
chi_commarea_geometries <- st_read("~/GitHub/Peoples Budget Viz/peoples-budget-viz/visualize/csvs", "commarea")

```


```{r cars}


#Get Centroids
chi_commarea_geometries <- chi_commarea_geometries %>%
      mutate(
            CENTROID = map(geometry, st_centroid),
            COORDS = map(CENTROID, st_coordinates),
            longitude = map_dbl(COORDS, 1),
            latitude = map_dbl(COORDS, 2)
      ) %>%
      select(-CENTROID, -COORDS) %>%
      select(community, shape_area:geometry)



chi_commarea_geometries$community = tolower(chi_commarea_geometries$community)
summary_commarea$CHI_COMM_AREA_NAME = tolower(summary_commarea$CHI_COMM_AREA_NAME)
names(summary_commarea)[names(summary_commarea) == "CHI_COMM_AREA_NAME"] <- "community"

merged = chi_commarea_geometries %>% left_join(summary_commarea, by = "community")
```

```{r}
##Vector Tiles
options(nextzen_API_key = "xSaj7h_dTAOvPb4PMBUn_Q")
mz_set_tile_host_nextzen(key = getOption("nextzen_API_key"))


get_vector_tiles <- function(bbox){
  mz_box=mz_rect(bbox$xmin,bbox$ymin,bbox$xmax,bbox$ymax)
  mz_vector_tiles(mz_box)
  }

bbox <- st_bbox(chi_commarea_geometries)

vector_tiles <- get_vector_tiles(bbox)

roads <- as_sf(vector_tiles$roads)

```

```{r}
#map
comm_map = ggplot(merged) + 
  geom_sf(aes(fill=count)) +  
  geom_sf(data = roads %>% filter(kind == "highway"), color="white", size = 0.4, alpha = 0.4) +
  scale_fill_viridis(direction = 1,
                     name = "People Responded", 
                     breaks = c(5, 10, 15, 20, 25, 30),
                     guide = guide_legend(keyheight = unit(3, units = "mm"), keywidth=unit(12, units = "mm"), 
                                          label.position = "bottom", title.position = 'top', nrow=6)) +
  coord_sf(datum = NA， xlim = c(-87.86011, -87.54414),ylim = c(41.65455, 42.01303)) +
  theme_void() +
  theme(axis.text.x=element_blank(), #remove axis data labels
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        panel.grid.major=element_line(colour="transparent"),
        legend.position = c(-.2,.8),
        legend.text = element_text(
          margin = margin(l = 5, unit = "pt")))

comm_map
```



```{r}


###Save as Image
ggsave(plot = comm_map, 
       width = 15, 
       height = 8 / 0.8125,
      "~/GitHub/Peoples Budget Viz/peoples-budget-viz/visualize/output/commmap.png",
       dpi=300)

```
