---
title: "ward map"
author: "Yi Ning"
date: "10/24/2020"
output: html_document
---
```{r}
list.of.packages <- c("tidyverse", 
                      "readr",
                      "usethis",
                      "sf",
                      "viridis",
                      "rmapzen"
                      )

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]

library()
if(length(new.packages)) install.packages(new.packages)

#load all required packages
lapply(list.of.packages, require, character.only = TRUE)
remove(list=ls())
```

```{r}

summary_ward = read.csv("~/GitHub/Peoples Budget Viz/peoples-budget-viz/visualize/csvs/Peoples_Budget_user_summary_WARD.csv")
chi_ward_geometries <- st_read("~/GitHub/Peoples Budget Viz/peoples-budget-viz/visualize/csvs", "wards")

```



```{r cars}


#Get Centroids
chi_ward_geometries <- chi_ward_geometries %>%
      mutate(
            CENTROID = map(geometry, st_centroid),
            COORDS = map(CENTROID, st_coordinates),
            longitude = map_dbl(COORDS, 1),
            latitude = map_dbl(COORDS, 2)
      ) %>%
      select(-CENTROID, -COORDS) %>%
      select(ward, shape_area:geometry)

colnames(summary_ward)[1] = "ward"
chi_ward_geometries = transform(chi_ward_geometries, ward = as.numeric(ward))
##Merge Data
merged = chi_ward_geometries %>% left_join(summary_ward, by = "ward")
```

```{r}
##Vector Tiles
options(nextzen_API_key = "xSaj7h_dTAOvPb4PMBUn_Q")
mz_set_tile_host_nextzen(key = getOption("nextzen_API_key"))


get_vector_tiles <- function(bbox){
  mz_box=mz_rect(bbox$xmin,bbox$ymin,bbox$xmax,bbox$ymax)
  mz_vector_tiles(mz_box)
  }

bbox <- st_bbox(chi_ward_geometries)


vector_tiles <- get_vector_tiles(bbox)

roads <- as_sf(vector_tiles$roads)

```

```{r}
#map
ward_map = 
  ggplot(merged) + 
  geom_sf(aes(fill=(count))) +  
  geom_sf(data = roads %>% filter(kind == "highway"), color="white", size = 0.4, alpha = 0.4) +
  scale_fill_viridis(direction = 1,
                     name = "People Responded", 
                     breaks=c(0, 5, 10,15, 20, 23),
                     guide = guide_legend(keyheight = unit(3, units = "mm"), keywidth=unit(12, units = "mm"), 
                                          label.position = "bottom", title.position = 'top', nrow=5)) +
  coord_sf(datum = NA， xlim = c(-87.86011, -87.54414),ylim = c(41.65455, 42.01303)) +
  theme_void() +
  theme(axis.text.x=element_blank(), #remove axis data labels
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        panel.grid.major=element_line(colour="transparent"),
        legend.position = c(-.12,.8),
        legend.text = element_text(
          margin = margin(l = 5, unit = "pt")))

ward_map
```



```{r}


###Save as Image
ggsave(plot = ward_map, 
       width = 12, 
       height = 8 / 0.8125,
      "~/GitHub/Peoples Budget Viz/peoples-budget-viz/visualize/output/wardmap_legend2.png",
       dpi=300)

```

**Interactive Map **
```{r}
##Interactive Ward Map

interactive_ward = ggplotly(wardmap, tooltip = c("ward", "count")) %>%  layout(annotations = 
 list(text = "Data: People's Budget Chicago | peoplesbudgetchicago.com.", 
      showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto', xshift=450, yshift=-150,
      font=list(size=9, color="black"))
 )

##save html code
htmlwidgets::saveWidget(as_widget(interactive_ward), "wardplotly.html")

```

